name: runtests
on:
  push: 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Run tests
      run: |
        go test -timeout 30s "./..."
    - name: Run checks
      run: |
        go vet "./..."